# Overrides for production environment
baseurl = "https://chivascollection.phanphoiruoungoai.net/"
[sitemap]
  changefreq = "monthly"
  disable = true
  filename = "sitemap.xml"
  priority = 0.5

[services]
  [services.googleAnalytics]
    ID = 'G-05FKBHYDFJ'
